name: "Camera Bot"
version: "1.0.0"
slug: "camera_bot"
description: "Discord Camera Bot with AI Analysis"
url: "https://github.com/yourusername/my_camera_bot"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ports:
  9000/tcp: 9000
options:
  discord_token: ""
  user_id: ""
  api_key: ""
  ollama_server: "http://192.168.1.96:11434"
  camera_server: "http://192.168.1.96:5000"
  camera_endpoints:
    front: "/api/Front/latest.jpg"
    back: "/api/Back/latest.jpg"
    shed: "/api/Shed/latest.jpg"
    road: "/api/Road/latest.jpg"
schema:
  discord_token: str
  user_id: str
  api_key: str
  ollama_server: str
  camera_server: str
  camera_endpoints:
    front: str
    back: str
    shed: str
    road: str
